### ISSUE TITLE
Does it support rtl?

### ISSUE THREAD

**Issue by meirlamdan** [smastrom/notivue#30]
[Here](https://notivue.smastrom.dev/) you bring an example of rtl
But nothing is mentioned in the documentation

**Comment by smastrom** [comment]
Hi @meirlamdan, like any other rtl website, all you need is to add a `dir="rtl"` attribute along with your website language (e.g. `lang="ar"`) to the `html` root element.

[https://www.w3.org/International/questions/qa-html-dir#rtlsetup](https://www.w3.org/International/questions/qa-html-dir#rtlsetup)

There's no configuration needed as your website is already supposed to have those attributes set if its language is not ltr (e.g. English).

Try to open the browser code inspector at [notivue.smastrom.dev/](https://notivue.smastrom.dev/) and look at the `html` node while you click on `Toggle RTL`.

If using Vite, simply set those attributes manually in your index.html file. If using Nuxt, you can set them via `nuxt.config.ts`:

```ts
export default defineNuxtConfig({
   app: {
      head: {
         htmlAttrs: {
            lang: 'ar',
            dir: 'rtl',
         },
      },
   },
})
```

**Comment by meirlamdan** [comment]
Thanks.
1. I think it should be documented
2. Maybe it should be possible to set rtl without having to depend on the setting the direction site, like [here](https://github.com/Maronato/vue-toastification#right-to-left-support) for example

**Comment by smastrom** [comment]
The best I can do is to guarantee that if your website is for example in arabic, built-in notifications are automatically directed accordingly both semantically and visually. I'm not implementing a prop or an option to do something which is part of the HTML itself (because people building arabic websites should not set a prop for that since are already applying the right attributes to the `html` node).

Now I'm not sure if I understood your requirement because with the acronym "RTL" you might be referring to two different concepts, so I'll give you answers for both.

### RTL Layout
You want to display the close button on the left, the text in its natural direction in the center, and the icon on the right regardless of the language. We're talking about horizontally inverting the elements because you prefer them like that and has nothing to do with RTL language support.

In this case you can add this CSS somewhere in order to achieve that:

```css
html:not([dir='rtl']) .Notivue__notification {
   flex-direction: row-reverse;
}

.Notivue__icon {
   margin: var(--nv-spacing) var(--nv-spacing) var(--nv-spacing) 0;
}

.Notivue__content {
   /* Set 'right' to see the text like the 1st notification below,
   or do not set it to see like the 2nd one */
   text-align: right;
}

.Notivue__close {
   margin: var(--nv-spacing) 0 var(--nv-spacing) var(--nv-spacing);
}
```

![Screenshot 2023-10-30 alle 14 18 41](https://github.com/smastrom/notivue/assets/60471784/762df1d5-f02e-4735-99b4-40ea8cab288e)

![Screenshot 2023-10-30 alle 14 36 40](https://github.com/smastrom/notivue/assets/60471784/e71d9552-663f-4626-9463-ee9b46cc72c0)

This doesn't need to be documented because built-in notifications are designed to have the icon on the left and the close on the right with LTR languages and viceversa. Whoever wants to change that can either hack into `notifications.css` or use [Custom Components](https://notivuedocs.netlify.app/custom-components/usage.html).

### RTL Language Support
The website developer (not me) tells the browser the language of the elements (and the direction) via the `lang` and `dir` attributes. To my knowledge, this is the only correct way to do that. In this case Notivue built-in notifications will ensure their appearance is directed accordingly.

Since anyone building arabic (or any other rtl language) website should know that, this doesn't need to be documented.

Moreover, I can't recall a single website that displayed multiple notifications with different languages and directions in the same page and that's the reason why I'm not implementing a way to forward those attributes to the notification container (similar to the package you linked).

If you really need to do that, the only way is to use custom components because built-in notifications are not designed nor supposed to support that.

This is how you would do that:

```vue
<script setup lang="ts">
import type { NotivueItem } from 'notivue'

export interface CustomProps {
  lang?: string
  dir?: string
}

const props = defineProps<{
  item: NotivueItem<CustomProps>
}>()
</script>

<template>
  <div :lang="item.props.lang || 'en'" :dir="item.props.dir || 'ltr'" class="Container">
    <p>{{ item.message }}</p>
    <button @click="item.clear">Dismiss</button>
  </div>
</template>

<style scoped>
.Container {
  /* Rules for LTR */
}

[dir='rtl'] .Container {
  /* Rules for RTL... */
}
</style/>
```

```vue
<script setup>
import { Notivue, type NotivueItem } from 'notivue'

import CustomNotification, { type CustomProps } from './CustomNotification.vue'

push.success({
 message: 'This is a notification',
 props: {
  lang: 'ar',
  dir: 'rtl',
})
</script>

<template>
  <Notivue v-slot="item">
    <CustomNotification :item="item as NotivueItem<CustomProps>" />
  </Notivue>

  <!-- RouterView, etc. -->
</template>
```

**Comment by smastrom** [comment]
The best I can do is to guarantee that if your website is for example in arabic, built-in notifications are automatically directed accordingly both semantically and visually. I'm not implementing a prop or an option to do something which is part of the HTML itself (because people building arabic websites should not set a prop for that since are already applying the right attributes to the `html` node).

Now I'm not sure if I understood your requirement because with the acronym "RTL" you might be referring to two different concepts, so I'll give you answers for both.

### RTL Layout
You want to display the close button on the left, the text in its natural direction in the center, and the icon on the right regardless of the language. We're talking about horizontally inverting the elements because you prefer them like that and has nothing to do with RTL language support.

In this case you can add this CSS somewhere in order to achieve that:

```css
html:not([dir='rtl']) .Notivue__notification {
   flex-direction: row-reverse;
}

.Notivue__icon {
   margin: var(--nv-spacing) var(--nv-spacing) var(--nv-spacing) 0;
}

.Notivue__content {
   /* Set 'right' to see the text like the 1st notification below,
   or do not set it to see like the 2nd one */
   text-align: right;
}

.Notivue__close {
   margin: var(--nv-spacing) 0 var(--nv-spacing) var(--nv-spacing);
}
```

![Screenshot 2023-10-30 alle 14 18 41](https://github.com/smastrom/notivue/assets/60471784/762df1d5-f02e-4735-99b4-40ea8cab288e)

![Screenshot 2023-10-30 alle 14 36 40](https://github.com/smastrom/notivue/assets/60471784/e71d9552-663f-4626-9463-ee9b46cc72c0)

This doesn't need to be documented because built-in notifications are designed to have the icon on the left and the close on the right with LTR languages and viceversa. Whoever wants to change that can either hack into `notifications.css` or use [Custom Components](https://notivuedocs.netlify.app/custom-components/usage.html).

### RTL Language Support
The website developer (not me) tells the browser the language of the elements (and the direction) via the `lang` and `dir` attributes. To my knowledge, this is the only correct way to do that. In this case Notivue built-in notifications will ensure their appearance is directed accordingly.

Since anyone building arabic (or any other rtl language) website should know that, this doesn't need to be documented.

Moreover, I can't recall a single website that displayed multiple notifications with different languages and directions in the same page and that's the reason why I'm not implementing a way to forward those attributes to the notification container (similar to the package you linked).

If you really need to do that, the only way is to use custom components because built-in notifications are not designed nor supposed to support that.

This is how you would do that:

```vue
<script setup lang="ts">
import type { NotivueItem } from 'notivue'

export interface CustomProps {
  lang?: string
  dir?: string
}

const props = defineProps<{
  item: NotivueItem<CustomProps>
}>()
</script>

<template>
  <div :lang="item.props.lang || 'en'" :dir="item.props.dir || 'ltr'" class="Container">
    <p>{{ item.message }}</p>
    <button @click="item.clear">Dismiss</button>
  </div>
</template>

<style scoped>
.Container {
  /* Rules for LTR */
}

[dir='rtl'] .Container {
  /* Rules for RTL... */
}
</style/>
```

```vue
<script setup lang="ts">
import { Notivue, type NotivueItem } from 'notivue'

import CustomNotification, { type CustomProps } from './CustomNotification.vue'

push.success({
 message: 'This is a notification',
 props: {
  lang: 'ar',
  dir: 'rtl',
})
</script>

<template>
  <Notivue v-slot="item">
    <CustomNotification :item="item as NotivueItem<CustomProps>" />
  </Notivue>

  <!-- RouterView, etc. -->
</template>
```

**Comment by smastrom** [comment]
The best I can do is to guarantee that if your website is for example in arabic, built-in notifications are automatically directed accordingly both semantically and visually. I'm not implementing a prop or an option to do something which is part of the HTML itself (because people building arabic websites should not set a prop for that since are already applying the right attributes to the `html` node).

Now I'm not sure if I understood your requirement because with the acronym "RTL" you might be referring to two different concepts, so I'll give you answers for both.

### RTL Layout
You want to display the close button on the left, the text in its natural direction in the center, and the icon on the right regardless of the language. We're talking about horizontally inverting the elements because you prefer them like that and has nothing to do with RTL language support.

In this case you can add this CSS somewhere in order to achieve that:

```css
html:not([dir='rtl']) .Notivue__notification {
   flex-direction: row-reverse;
}

.Notivue__icon {
   margin: var(--nv-spacing) var(--nv-spacing) var(--nv-spacing) 0;
}

.Notivue__content {
   /* Set 'right' to see the text like the 1st notification below,
   or do not set it to see like the 2nd one */
   text-align: right;
}

.Notivue__close {
   margin: var(--nv-spacing) 0 var(--nv-spacing) var(--nv-spacing);
}
```

![Screenshot 2023-10-30 alle 14 18 41](https://github.com/smastrom/notivue/assets/60471784/762df1d5-f02e-4735-99b4-40ea8cab288e)

![Screenshot 2023-10-30 alle 14 36 40](https://github.com/smastrom/notivue/assets/60471784/e71d9552-663f-4626-9463-ee9b46cc72c0)

This doesn't need to be documented because built-in notifications are designed to have the icon on the left and the close on the right with LTR languages and viceversa. Whoever wants to change that can either hack into `notifications.css` or use [Custom Components](https://notivuedocs.netlify.app/custom-components/usage.html).

### RTL Language Support
The website developer (not me) tells the browser the language of the elements (and the direction) via the `lang` and `dir` attributes. To my knowledge, this is the only correct way to do that. In this case Notivue built-in notifications will ensure their appearance is directed accordingly.

Since anyone building arabic (or any other rtl language) website should know that, this doesn't need to be documented.

Moreover, I can't recall a single website that displayed multiple notifications with different languages and directions in the same page and that's the reason why I'm not implementing a way to forward those attributes to the notification container (similar to the package you linked).

If you really need to do that, the only way is to use custom components because built-in notifications are not designed nor supposed to support that.

This is how you would do that:

```vue
<script setup lang="ts">
import type { NotivueItem } from 'notivue'

export interface CustomProps {
  lang?: string
  dir?: string
}

const props = defineProps<{
  item: NotivueItem<CustomProps>
}>()
</script>

<template>
  <div :lang="item.props.lang || 'en'" :dir="item.props.dir || 'ltr'" class="Container">
    <p>{{ item.message }}</p>
    <button @click="item.clear">Dismiss</button>
  </div>
</template>

<style scoped>
.Container {
  /* Rules for LTR... */
}

[dir='rtl'] .Container {
  /* Rules for RTL... */
}
</style/>
```

```vue
<script setup lang="ts">
import { Notivue, type NotivueItem } from 'notivue'

import CustomNotification, { type CustomProps } from './CustomNotification.vue'

push.success({
  message: 'This is a notification',
  props:
    lang: 'ar',
    dir: 'rtl',
  },
})
</script>

<template>
  <Notivue v-slot="item">
    <CustomNotification :item="item as NotivueItem<CustomProps>" />
  </Notivue>

  <!-- RouterView, etc. -->
</template>
```

**Comment by smastrom** [comment]
The best I can do is to guarantee that if your website is for example in arabic, built-in notifications are automatically directed accordingly both semantically and visually. I'm not implementing a prop or an option to do something which is part of the HTML itself (because people building arabic websites should not set a prop for that since are already applying the right attributes to the `html` node).

Now I'm not sure if I understood your requirement because with the acronym "RTL" you might be referring to two different concepts, so I'll give you answers for both.

### RTL Layout
You want to display the close button on the left, the text in its natural direction in the center, and the icon on the right regardless of the language. We're talking about horizontally inverting the elements because you prefer them like that and has nothing to do with RTL language support.

In this case you can add this CSS somewhere in order to achieve that:

```css
html:not([dir='rtl']) .Notivue__notification {
   flex-direction: row-reverse;
}

.Notivue__icon {
   margin: var(--nv-spacing) var(--nv-spacing) var(--nv-spacing) 0;
}

.Notivue__content {
   /* Set 'right' to see the text like the 1st notification below,
   or do not set it to see like the 2nd one */
   text-align: right;
}

.Notivue__close {
   margin: var(--nv-spacing) 0 var(--nv-spacing) var(--nv-spacing);
}
```

![Screenshot 2023-10-30 alle 14 18 41](https://github.com/smastrom/notivue/assets/60471784/762df1d5-f02e-4735-99b4-40ea8cab288e)

![Screenshot 2023-10-30 alle 14 36 40](https://github.com/smastrom/notivue/assets/60471784/e71d9552-663f-4626-9463-ee9b46cc72c0)

This doesn't need to be documented because built-in notifications are designed to have the icon on the left and the close on the right with LTR languages and viceversa. Whoever wants to change that can either hack into `notifications.css` or use [Custom Components](https://notivuedocs.netlify.app/custom-components/usage.html).

### RTL Language Support
The website developer (not me) tells the browser the language of the elements (and the direction) via the `lang` and `dir` attributes. To my knowledge, this is the only correct way to do that. In this case Notivue built-in notifications will ensure their appearance is directed accordingly.

Since anyone building arabic (or any other rtl language) website should know that, this doesn't need to be documented.

Moreover, I can't recall a single website that displayed multiple notifications with different languages and directions in the same page and that's the reason why I'm not implementing a way to forward those attributes to the notification container (similar to the package you linked).

If you really need to do that, the only way is to use custom components because built-in notifications are not designed nor supposed to support that.

This is how you would do that:

```vue
<script setup lang="ts">
import type { NotivueItem } from 'notivue'

export interface CustomProps {
  lang?: string
  dir?: string
}

defineProps<{
  item: NotivueItem<CustomProps>
}>()
</script>

<template>
  <div :lang="item.props.lang || 'en'" :dir="item.props.dir || 'ltr'" class="Container">
    <p>{{ item.message }}</p>
    <button @click="item.clear">Dismiss</button>
  </div>
</template>

<style scoped>
.Container {
  /* Rules for LTR... */
}

[dir='rtl'] .Container {
  /* Rules for RTL... */
}
</style/>
```

```vue
<script setup lang="ts">
import { Notivue, type NotivueItem } from 'notivue'

import CustomNotification, { type CustomProps } from './CustomNotification.vue'

push.success({
  message: 'This is a notification',
  props:
    lang: 'ar',
    dir: 'rtl',
  },
})
</script>

<template>
  <Notivue v-slot="item">
    <CustomNotification :item="item as NotivueItem<CustomProps>" />
  </Notivue>

  <!-- RouterView, etc. -->
</template>
```
